"""empty message

Revision ID: 1135a45f03a3
Revises: 
Create Date: 2024-11-14 12:43:05.541506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1135a45f03a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'CLOSED', name='itemstatus').create(op.get_bind())
    sa.Enum('LOST', 'FOUND', name='itemtypes').create(op.get_bind())
    sa.Enum('NONE', 'ADMINISTRATOR', name='userpermissions').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('permissions', postgresql.ENUM('NONE', 'ADMINISTRATOR', name='userpermissions', create_type=False), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', postgresql.ENUM('LOST', 'FOUND', name='itemtypes', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CLOSED', name='itemstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('users')
    sa.Enum('NONE', 'ADMINISTRATOR', name='userpermissions').drop(op.get_bind())
    sa.Enum('LOST', 'FOUND', name='itemtypes').drop(op.get_bind())
    sa.Enum('ACTIVE', 'CLOSED', name='itemstatus').drop(op.get_bind())
    # ### end Alembic commands ###
