"""empty message

Revision ID: fada1187f62a
Revises: 
Create Date: 2025-01-26 18:47:06.784345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fada1187f62a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'CLOSED', name='itemstatus').create(op.get_bind())
    sa.Enum('LOST', 'FOUND', name='itemtypes').create(op.get_bind())
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', postgresql.ENUM('LOST', 'FOUND', name='itemtypes', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'CLOSED', name='itemstatus', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    sa.Enum('LOST', 'FOUND', name='itemtypes').drop(op.get_bind())
    sa.Enum('ACTIVE', 'CLOSED', name='itemstatus').drop(op.get_bind())
    # ### end Alembic commands ###
